// Simple in-memory cache for storing angles generated by the Intelligence Engine
// This ensures Zero-Trust: the client can only request generation for an angle
// that was actually generated by the server.

export interface CachedAngle {
  id: string;
  intent: string;
  title: string;
  angleSummary: string;
  audience: string;
  audienceValue: string;
  evidenceIds: string[];
  supportLevel: string;
  humanInsightGap?: string;
  requiresHumanContext: boolean;
  adaptiveQuestion?: string;
  recommended: boolean;
  tone: string;
  claimRisk: string;
}

export interface CachedAnalysis {
  timestamp: number;
  angles: CachedAngle[];
}

const analysisCache = new Map<string, CachedAnalysis>();

// Cleanup old cache entries (older than 1 hour)
function cleanupCache() {
  const now = Date.now();
  for (const [key, value] of analysisCache.entries()) {
    if (now - value.timestamp > 60 * 60 * 1000) {
      analysisCache.delete(key);
    }
  }
}

export function saveAnalysisToCache(repoUrl: string, angles: CachedAngle[]) {
  cleanupCache();
  // We use repoUrl as the key for simplicity in the demo.
  // In a real app with users, we would use a combination of userId and repoUrl or a unique sessionId.
  analysisCache.set(repoUrl, {
    timestamp: Date.now(),
    angles
  });
}

export function getAngleFromCache(repoUrl: string, angleId: string): CachedAngle | null {
  cleanupCache();
  const cached = analysisCache.get(repoUrl);
  if (!cached) return null;
  
  return cached.angles.find(a => a.id === angleId) || null;
}
